# Generated by Django 5.1.4 on 2025-12-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesacalls',
            name='conversation_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
