# Generated by Django 5.1.4 on 2025-12-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_api", "0001_initial"),
        ("mpesa_api", "0002_alter_mpesacalls_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesapayment",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mpesa_payments",
                to="business_api.business",
            ),
        ),
        migrations.AddField(
            model_name="mpesapayment",
            name="shortcode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mpesa_payments",
                to="business_api.mpesashortcode",
            ),
        ),
        migrations.CreateModel(
            name="StkPushInitiation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("merchant_request_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("checkout_request_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("account_reference", models.CharField(blank=True, default="", max_length=64)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stk_push_initiations",
                        to="business_api.business",
                    ),
                ),
                (
                    "shortcode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stk_push_initiations",
                        to="business_api.mpesashortcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
