# Generated by Django 5.1.4 on 2025-12-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_api', '0001_initial'),
        ('mpesa_api', '0003_business_tenancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesacallbacks',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_callbacks', to='business_api.business'),
        ),
        migrations.AddField(
            model_name='mpesacallbacks',
            name='shortcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_callbacks', to='business_api.mpesashortcode'),
        ),
        migrations.AddField(
            model_name='mpesacalls',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_calls', to='business_api.business'),
        ),
        migrations.AddField(
            model_name='mpesacalls',
            name='shortcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_calls', to='business_api.mpesashortcode'),
        ),
    ]
