# Generated by Django 5.1.15 on 2025-12-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0005_mpesatransactionstatusquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='stkpushinitiation',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
