# Generated by Django 5.1.15 on 2025-12-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCodeMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_system', models.CharField(choices=[('safaricom', 'Safaricom'), ('gateway', 'Gateway')], max_length=20)),
                ('external_code', models.CharField(max_length=80)),
                ('internal_code', models.PositiveIntegerField(unique=True)),
                ('default_message', models.TextField(blank=True, default='')),
                ('is_success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['internal_code'],
                'constraints': [models.UniqueConstraint(fields=('external_system', 'external_code'), name='uniq_status_code_mapping_external')],
            },
        ),
    ]
