# Generated by Django 5.1.4 on 2025-12-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("business_api", "0001_initial"),
		("b2c_api", "0001_initial"),
	]

	operations = [
		migrations.AddField(
			model_name="bulkpayoutbatch",
			name="business",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="b2c_batches",
				to="business_api.business",
			),
		),
	]
