# Generated by Django 5.1.4 on 2025-12-27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("business_api", "0001_initial"),
		("b2c_api", "0002_batch_business"),
	]

	operations = [
		migrations.CreateModel(
			name="B2CPaymentRequest",
			fields=[
				("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				("environment", models.CharField(blank=True, default="", max_length=20)),
				("originator_conversation_id", models.CharField(max_length=100, unique=True)),
				("conversation_id", models.CharField(blank=True, default="", max_length=100)),
				("response_code", models.CharField(blank=True, default="", max_length=50)),
				("response_description", models.TextField(blank=True, default="")),
				("status", models.CharField(default="queued", max_length=20)),
				("request_payload", models.JSONField(blank=True, default=dict)),
				("api_response_payload", models.JSONField(blank=True, default=dict)),
				("api_error_payload", models.JSONField(blank=True, default=dict)),
				("callback_result_payload", models.JSONField(blank=True, default=dict)),
				("callback_timeout_payload", models.JSONField(blank=True, default=dict)),
				("result_code", models.IntegerField(blank=True, null=True)),
				("result_desc", models.TextField(blank=True, default="")),
				("transaction_id", models.CharField(blank=True, default="", max_length=100)),
				(
					"business",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="b2c_payment_requests",
						to="business_api.business",
					),
				),
				(
					"bulk_item",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="payment_requests",
						to="b2c_api.bulkpayoutitem",
					),
				),
			],
			options={
				"ordering": ["-created_at"],
			},
		),
	]
