# Generated by Django 5.1.15 on 2025-12-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_api', '0003_b2c_payment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cpaymentrequest',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='bulkpayoutitem',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
