# Generated by Django 5.1.15 on 2025-12-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_api', '0004_b2cpaymentrequest_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cpaymentrequest',
            name='internal_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2cpaymentrequest',
            name='internal_status_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
