# Generated by Django 5.1.4 on 2025-12-27 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_api', '0002_batch_business'),
        ('business_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BUSSDPushRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(blank=True, default='', max_length=20)),
                ('request_ref_id', models.CharField(max_length=100, unique=True)),
                ('response_code', models.CharField(blank=True, default='', max_length=50)),
                ('response_status', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='queued', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('api_response_payload', models.JSONField(blank=True, default=dict)),
                ('api_error_payload', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('result_code', models.CharField(blank=True, default='', max_length=50)),
                ('result_desc', models.TextField(blank=True, default='')),
                ('amount', models.CharField(blank=True, default='', max_length=30)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('conversation_id', models.CharField(blank=True, default='', max_length=120)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=120)),
                ('callback_status', models.CharField(blank=True, default='', max_length=40)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_ussd_push_requests', to='business_api.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
