# Generated by GitHub Copilot

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mpesa_api", "0002_alter_mpesacalls_conversation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="QrCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("merchant_name", models.CharField(max_length=200)),
                ("ref_no", models.CharField(db_index=True, max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("trx_code", models.CharField(max_length=10)),
                ("cpi", models.CharField(blank=True, max_length=120)),
                ("size", models.CharField(blank=True, max_length=20)),
                ("request_payload", models.JSONField(default=dict)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_payload", models.JSONField(default=dict)),
                ("qr_code_base64", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code",
                "verbose_name_plural": "QR Codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
