# Generated by Django 5.1.4 on 2025-12-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'verbose_name': 'QR Code', 'verbose_name_plural': 'QR Codes'},
        ),
    ]
