# Generated by Django 5.1.15 on 2025-12-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_api', '0003_mpesashortcode_default_ratiba_callback_url'),
        ('qr_api', '0002_alter_qrcode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='business_api.business'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='shortcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='business_api.mpesashortcode'),
        ),
    ]
