# Generated by Django 5.1.15 on 2025-12-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_api', '0003_qrcode_business_qrcode_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='internal_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='internal_status_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
