# Generated by Django 5.1.15 on 2025-12-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_api', '0002_oauthclientbusiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesashortcode',
            name='default_ratiba_callback_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
