# Generated by Django 5.1.15 on 2025-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_api', '0003_mpesashortcode_default_ratiba_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesashortcode',
            name='txn_status_identifier_type',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='mpesashortcode',
            name='txn_status_initiator_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='mpesashortcode',
            name='txn_status_result_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mpesashortcode',
            name='txn_status_security_credential',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mpesashortcode',
            name='txn_status_timeout_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
