# Generated by Django 5.1.15 on 2025-12-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_api', '0004_mpesashortcode_txn_status_identifier_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
