# Generated by GitHub Copilot

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mpesa_api", "0002_alter_mpesacalls_conversation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatibaOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_payload", models.JSONField(default=dict)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_payload", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ratiba_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ratiba Order",
                "verbose_name_plural": "Ratiba Orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
