# Generated by Django 5.1.4 on 2025-12-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratiba_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratibaorder',
            options={'verbose_name': 'Ratiba Order', 'verbose_name_plural': 'Ratiba Orders'},
        ),
    ]
