# Generated by Django 5.1.15 on 2025-12-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratiba_api', '0004_ratibaorder_business_ratibaorder_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratibaorder',
            name='internal_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratibaorder',
            name='internal_status_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
